services:
  db:
    image: mariadb:10.11
    container_name: ${CONTAINER_DB}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moodle-net

  moodle:
    image: moodle-custom:latest
    container_name: ${CONTAINER_MOODLE}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - moodle-net

networks:
  moodle-net:
    driver: bridge

volumes:
  db_data:
    external: true   
    name: moodle-migration_db_data