version: '3.8'

services:
  db:
    image: mariadb:10.6
    container_name: moodle-db-migration
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moodle-net

  moodle:
    image: migration-moodle:latest
    container_name: moodle-migration
    restart: always
    ports:
      - "80:80"
    environment:
      PHP_INI-upload_max_filesize: ${PHP_INI_upload_max_filesize}
      PHP_INI-post_max_size: ${PHP_INI_post_max_size}
    depends_on:
      - db
    networks:
      - moodle-net

networks:
  moodle-net:
    driver: bridge

volumes:
  db_data:
    external: true   
    name: moodle-migration_db_data